version: "3.9"

services:
  icyarr:
    container_name: icyarr
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./channel.db:/app/channel.db
    restart: unless-stopped

  icyarr-frontend:
    container_name: icyarr-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
